branch-defaults:
  master:
    environment: driversklub-backend-env
  staging:
    environment: driversklub-backend-staging-env
environment-defaults:
  driversklub-backend-prod:
    branch: null
    repository: null
global:
  application_name: driversklub-backend
  branch: null
  default_ec2_keyname: driversklub-eb-key
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
